# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 13

    providers:
        in_memory:
            memory: 
                users:
                    admin:
                        password: $2y$13$O3zxXqlWgAk/LyFhTxzXOO1uhStRw2nr0G/hB4MKf73K/DoNJ6MbG
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        admin_secured_area:
            pattern: ^/admin/
            http_basic:
                realm: "Secured Admin Area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
